name: Daruma
version: 1.0
main: daruma.daruma.Daruma
commands:
  daruma:
    description: ダルマコマンド

  setstartpoint:
    description: スタート地点を設定します。

  turn:
    description: ターン数を指定します

  start:
    description: ゲームを開始します

  end:
    description: ゲームを強制終了させます。

  rank:
    description: ランキングを表示します

permissions:
  Daruma:
    default: op
